### ISSUE TITLE
Support hapi path parameters

### ISSUE THREAD

**Issue by arneg** [rse/hapi-plugin-websocket#2]
Unfortunately, path parameters are not supported.

**Comment by rse** [comment]
What makes you think this is true? Please see the example under https://github.com/rse/hapi-plugin-websocket. The HAPI Path parameter is supported just fine. But perhaps I do not understand your issue correctly. Can you be more specific please?

**Comment by arneg** [comment]
Yes, sorry for the brief comment. This was really not a very good bug report. I was somehow in a hurry, I should have posted this later.

The path parameter which I was talking about are ones of the form "/{foo}/{bar}" for instance. I could not get those to work, but maybe I misunderstood the examples.

Sorry again.

**Comment by DeanBDean** [comment]
@arneg So the issue is with [ws](https://www.npmjs.com/package/ws). Currently this plugin passes path into ws as the path for the websocket server. Unfortunately, as far as I can tell, ws does not allow for path parameters. One workaround would be to use query parameters, and then parse the query parameters in a connect method in the plugin options. The other option I see would be to just connect to an endpoint that doesn't have path or query params, and then immediately send any params through the socket after the connection.

**Comment by rse** [comment]
Yes, indeed. That's the problem: "ws" does support a path, but not with parameters. Hmmm...

**Comment by arneg** [comment]
Maybe it's not a huge issue in itself. In that case, it might be good to mention it in the documentation. I ended up putting all information into the query string, which of course also works.

**Comment by rse** [comment]
I've now added a check so an exception will be thrown if one uses a path with a parameter value. This way one at least recognizes the incompatibility between HAPI and WebSocket paths.

**Comment by rse** [comment]
I've now rewritten the plugin and it now even supports HAPI path parameters.

**Comment by arneg** [comment]
Very cool, thank you very much.
